[general]
import = ["~/config/alacritty/breeze.toml",]

[font]
size = 12.0

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "hack"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[scrolling]
history = 100000

