set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'Valloric/YouCompleteMe'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'mhinz/vim-signify'

Plugin 'bling/vim-bufferline'

Plugin 'sjl/gundo.vim'

Plugin 'lervag/vimtex'
Plugin 'sirver/ultisnips'

Plugin 'madox2/vim-ai'

Plugin 'rickhowe/diffchar.vim'
Plugin 'rickhowe/wrapfiller'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on     " iequired!
"
"" Brief help
" :PluginList       - lists configured plugins
" " :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " :PluginClean      - confirms removal of unused plugins; append `!` to
" auto-approve removal
" "
" " see :h vundle for more details or wiki for FAQ
" " Put your non-Plugin stuff after this line


" leader is comma
let mapleader = ","
let maplocalleader = ','
" jk is escape
inoremap jk <esc>
" default to not read-only in vimdiff
set noro
nnoremap <silent> <leader>dp V:diffput<cr>
nnoremap <silent> <leader>do V:diffget<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugins
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"ycm
let g:ycm_confirm_extra_conf = 0
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_complete_in_comments=1
let g:ycm_show_detailed_diag_in_popup=1


"octave
augroup filetypedetect
  au! BufRead,BufNewFile *.m,*.oct set filetype=octave
augroup END

if has("autocmd") && exists("+omnifunc")
  autocmd Filetype octave
    \ if &omnifunc == "" |
    \ setlocal omnifunc=syntaxcomplete#Complete |
    \ endif
endif

" toggle gundo
nnoremap <leader>u :GundoToggle<CR>

"signify
let g:signify_vcs_list = ['hg', 'git']
let g:signify_update_on_focusgained = 1

"vimtex +ycm
if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
  endif
  let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme

"vimtex
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_autoclose_after_keystrokes = 2
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_automatic = 0
let g:vimtex_view_use_temp_files = 1
let g:vimtex_compiler_latexmk_engines = {'_':'-lualatex'}
let g:vimtex_compiler_latexmk = {
        \'options' : [
        \   '-verbose',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \   '-shell-escape',
        \ ],
        \}


" UltiSnips
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
"  - ctrl-j to expand
"  - ctrl-j to go to next tabstop
"  - ctrl-k to go to previous tabstop
let g:UltiSnipsExpandTrigger = '<C-j>'
let g:UltiSnipsJumpForwardTrigger = '<C-j>'
let g:UltiSnipsJumpBackwardTrigger = '<C-k>'

" vim_ai
let g:vim_ai_roles_config_file = $HOME.'/.vim/airoles.ini'
let initial_prompt =<< trim END
>>> system

You are going to play a role of a completion engine with following parameters:
Task: Provide compact code/text completion, generation, transformation or explanation
Topic: general programming and text editing for academic writing
Style: Plain result without any commentary, unless commentary is necessary
Audience: Users of text editor and programmers that need to transform/generate text
END

let chat_engine_config = {
\  "engine": "chat",
\  "options": {
\    "model": "gpt-4o",
\    "endpoint_url": "https://api.openai.com/v1/chat/completions",
\    "max_tokens": 3000,
\    "temperature": 0.1,
\    "request_timeout": 20,
\    "selection_boundary": "",
\    "initial_prompt": initial_prompt,
\  },
\}

let g:vim_ai_complete = chat_engine_config
let g:vim_ai_edit = chat_engine_config

let s:initial_chat_prompt =<< trim END
>>> system

You are a general assistant.
If you attach a code block add syntax type after ``` to enable syntax highlighting.
END

let g:vim_ai_chat = {
\  "options": {
\    "model": "gpt-4o",
\    "endpoint_url": "https://api.openai.com/v1/chat/completions",
\    "max_tokens": 3000,
\    "temperature": 0.8,
\    "request_timeout": 20,
\    "enable_auth": 1,
\    "selection_boundary": "",
\    "initial_prompt": s:initial_chat_prompt,
\  },
\  "ui": {
\    "code_syntax_enabled": 1,
\    "populate_options": 0,
\    "open_chat_command": "preset_below",
\    "scratch_buffer_keep_open": 0,
\    "paste_mode": 1,
\  },
\}

let g:vim_ai_debug = 0
let g:vim_ai_debug_log_file = "/dev/shm/vim_ai_debug.log"

" diffchar
nmap <silent> <leader>o <Plug>GetDiffCharPair
let g:DiffColors=3

" air-line
let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => VIM user interface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"background
set background=dark
colorscheme desert

" Enable syntax highlighting
syntax enable

" load filetype-specific indent files
filetype indent on

" Turn on the WiLd menu
set wildmenu

" Ignore compiled files
set wildignore=*.o,*~,*.pyc
if has("win16") || has("win32")
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
else
    set wildignore+=.git\*,.hg\*,.svn\*
endif

"Always show current position
"set ruler

"Show status
set laststatus=2

"number
set number
set relativenumber

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases
set smartcase
"
" Start search while typing
set incsearch

" Highlight search results
set hlsearch

" turn off search highlight
" nnoremap <leader><space> :nohlsearch<CR>

" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set mat=2

"highlight column
set colorcolumn=80
set colorcolumn+=120
highlight Pmenu ctermfg=15 ctermbg=0 guifg=#ffffff guibg=#000000
highlight ColorColumn ctermbg=238

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Text, tab and indent related
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Use spaces instead of tabs
set expandtab
"backspace for insert
set backspace=indent,eol,start

" Be smart when using tabs ;)
set smarttab

" 1 tab == 4 spaces
set shiftwidth=2
set tabstop=2

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines
set linebreak "Wrap by word
set diffopt+=followwrap "Wrap in diff

setlocal spell
set spelllang=en_gb
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => VIM yank buffers
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"increase the size of buffers
set viminfo='50,<1000,s1000,h


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => VIM user interface
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Moving around, tabs, windows and buffers
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Treat long lines as break lines (useful when moving around in them)
map j gj
map k gk

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal! g'\"" | endif
endif

" Allow saving of files as sudo when I forgot to start vim using sudo
cmap w!! w !sudo tee > /dev/null %

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Moving around, tabs, windows and buffers
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set indentexpr=GetIndent()

function GetIndent()
  let lnum = prevnonblank(v:lnum - 1)
  let ind = indent(lnum)
  return ind
endfunction

function! InsertPetscCall()
  normal SPetscCall());
  normal hh
  startinsert
endfunction
noremap <leader>e :call InsertPetscCall()<CR>

function! InsertCcomment()
  normal a /*  */
  normal hh
  startinsert
endfunction
noremap <leader>c :call InsertCcomment()<CR>

function! StripTrailingWhitespaces()
  if !&binary && &filetype != 'diff'
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
  endif
endfun
autocmd BufWritePre,FileWritePre,FileAppendPre,FilterWritePre * :call StripTrailingWhitespaces()

func! GrammarCheckFn() abort range
    let lines = getline(1, a:lastline)
    botright vnew | setlocal nobuflisted buftype=nofile bufhidden=wipe noswapfile ft=tex
    call setline(1, lines)
    exe a:firstline.','.a:lastline .'AIEdit /grammar'
    windo diffthis
    call cursor(a:firstline, 1)
endfunc
command! -range GrammarCheck <line1>,<line2>call GrammarCheckFn()
xnoremap <leader>g :GrammarCheck<CR>
